name: Java CI with Maven

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up GraalVM
      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21.0.0'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: 'maven'
          native-image-job-reports: 'true'

      # Step 3: Install Maven
      - name: Set up Maven
        run: sudo apt-get install maven

      # Step 4: Run the tests
      - name: Run tests with debug logging
        run: |
          # Enabling debug logging to get more detailed error output
          echo "micronaut.logging.level.io.micronaut=DEBUG" >> src/main/resources/application.yml
          mvn clean install -X
          mvn test -X
