name: Test GraalWasm Micronaut Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run-tests:
    name: 'Run GraalWasm Micronaut Tests'
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up GraalVM
      - name: Set up GraalVM with Java 24.0.0
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '24.0.0'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: 'maven'
          native-image-job-reports: 'true'

      # Step 3: Set up Maven
      - name: Set up Maven
        run: sudo apt-get install maven

      # Step 4: Build the project and run tests
      - name: Run tests
        run: |
          cd graalwasm/graalwasm-micronaut-photon
          ./mvnw clean test

      # (Optional) Step 5: Run the app locally and test the /download and /upload endpoints
      - name: Build native 'graalwasm-micronaut-photon'
        run: |
          cd graalwasm/graalwasm-micronaut-photon
          ./mvnw clean package -Dpackaging=native-image
          ./target/demo &
          sleep 10  # Wait for the app to start

          # Test /upload endpoint
          curl --fail-with-body --silent --dump-header - -o /dev/null -X POST http://localhost:8080/upload \
            -F "file=@path/to/your/file" # Replace with an actual file path to test file upload

          # Test /download endpoint
          curl --fail-with-body --silent --dump-header - -o downloaded_file http://localhost:8080/download \
            # Adjust the download URL parameters if necessary

