name: Test GraalWasm Micronaut Photon Demo
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: read
jobs:
  run:
    name: 'graalwasm-micronaut-excelize'
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21.0.0'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: 'maven'
          native-image-job-reports: 'true'
      - name: Package 'graalwasm-micronaut-photon'
        run: |
          
          ./mvnw --no-transfer-progress clean package
      - name: Build native 'graalwasm-micronaut-photon'
        run: |
          cd graalwasm/graalwasm-micronaut-photon
          ./mvnw --no-transfer-progress clean package -Dpackaging=native-image
          ./target/demo &
          sleep 10
          curl --fail-with-body --silent --dump-header - -o /dev/null http://localhost:8080/
